# Generic GNU makefile for CTEST under CVS/SRT.
#
# 07aug98 dla
#
# Copy this file (GNUmakefile.ctest) to GNUmakefile in each
# active directory.
#

include ctbuild/srt/srt.mk

# Example of how to display gmake symbols.
# COMMAND := $(shell echo CPPFLAGS = $(CPPFLAGS) >&2 )
