# Makefile for the compilation of the example under d0mino. 
# It links correct libz library associated with p13.10.00 release

CPP=KCC
LD=KCC
SPECIALFLAGS=--thread_safe --exceptions
ROOTCFLAGS=$(shell root-config --cflags)
ROOTLIBS=$(shell root-config --libs)

CFLAGS = $(SPECIALFLAGS) -I- -I../../include \
         -I/d0usr/products/zlib/IRIX/v1_1_4-fast/include
LFLAGS = $(SPECIALFLAGS) -L../../lib/$(SRT_SUBDIR)/ -llm_access \
         -L/d0usr/products/zlib/IRIX/v1_1_4-fast/lib/ -lz

RCXX=$(CFLAGS) $(ROOTCFLAGS)
RLXX=$(LFLAGS) $(ROOTLIBS)

all: examples

examples: example_xsec example_tick test_stage3

example_xsec.o: example_xsec.cpp
	$(CPP) $(RCXX) -c example_xsec.cpp
example_xsec: example_xsec.o
	$(LD) example_xsec.o $(RLXX) -o example_xsec
example_tick.o: example_tick.cpp
	$(CPP) $(RCXX) -c example_tick.cpp
example_tick: example_tick.o
	$(LD) example_tick.o $(RLXX) -o example_tick
test_stage3: test_stage3.o
	$(LD) test_stage3.o  $(LFLAGS) -o test_stage3
test_stage3.o: test_stage3.cpp
	$(CPP) $(CFLAGS) -c test_stage3.cpp

clean:
	rm -rf ti_files
	rm -f *~ *.o
	rm -f example_xsec example_tick test_stage3

